---
abstract: 'Smarty compatible template engine on Xslate'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Text::Clevy
name: Text-Clevy
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Any::Moose: 0.13
  Config::Tiny: 2.12
  HTML::Entities: 1.35
  Image::Size: 3.22
  Plack: 0.9938
  Text::Xslate: 0.1048
  Time::Piece: 1.12
  URI::Escape: 3.3
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Text-Clevy.git
version: 0.0001_02
